import { useState, useMemo, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Link2, Hash, RefreshCw, XCircle, Clock, Info, AlertCircle, CheckCircle2, Sparkles, Wallet, Zap, ChevronRight } from 'lucide-react';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { useAuth } from '@/lib/auth';
import { useToast } from '@/lib/toast';
import { useQuery } from '@/lib/useQuery';
import { fetchServices, fetchCategories, createOrder } from '@/lib/services';
import { formatCurrency, formatNumber, cn } from '@/lib/utils';
import type { IService, ICategory } from '@/lib/types';

export function NewOrderPage() {
  const { profile, refreshProfile } = useAuth(); const { toast } = useToast();
  const { data: categories } = useQuery(() => fetchCategories(), []); const { data: services } = useQuery(() => fetchServices(), []);
  const catList=(categories??[]) as ICategory[]; const svcList=(services??[]) as IService[];
  const [categoryId,setCategoryId]=useState(''); const [serviceId,setServiceId]=useState(''); const [link,setLink]=useState(''); const [quantity,setQuantity]=useState(100); const [submitting,setSubmitting]=useState(false); const [success,setSuccess]=useState(false);
  useEffect(()=>{if(catList.length&&!categoryId)setCategoryId(catList[0].id)},[catList,categoryId]);
  useEffect(()=>{const list=svcList.filter(s=>s.category_id===categoryId); if(list.length&&!serviceId)setServiceId(list[0].id)},[categoryId,svcList,serviceId]);
  const categoryServices=svcList.filter(s=>s.category_id===categoryId); const service=svcList.find(s=>s.id===serviceId);
  const charge=useMemo(()=>service?(Number(service.price)*quantity)/1000:0,[service,quantity]); const balance=profile?.balance??0;
  const linkError=link&&!link.match(/^https?:\/\/.+/)?'Link không hợp lệ. Phải bắt đầu bằng http(s)://':'';
  const qtyError=quantity>0&&service&&(quantity<service.minimum||quantity>service.maximum)?`Số lượng phải từ ${formatNumber(service.minimum)} đến ${formatNumber(service.maximum)}`:'';
  const balanceError=charge>balance?'Số dư không đủ. Vui lòng nạp tiền.':''; const canSubmit=!!link&&!linkError&&!qtyError&&!balanceError&&quantity>0&&!!service&&!submitting;
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!canSubmit||!service)return;setSubmitting(true);setSuccess(false);const result=await createOrder(service.id,link,quantity);setSubmitting(false);if(result.success){setSuccess(true);toast('Đơn hàng đã được tạo thành công!','success');refreshProfile();setLink('');setQuantity(100);setTimeout(()=>setSuccess(false),3500)}else toast(result.message??'Tạo đơn hàng thất bại','error')};
  return <div className="space-y-6">
    <div className="relative overflow-hidden rounded-2xl border border-primary-500/20 bg-gradient-to-br from-primary-500/12 via-bg-card to-secondary-500/10 p-5 sm:p-7"><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-primary-500/10 blur-3xl"/><div className="relative flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-primary-300 mb-2"><Sparkles className="h-3.5 w-3.5"/> 9L Media Order Center</div><h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">Tạo đơn hàng</h1><p className="text-sm text-text-muted mt-1.5">Chọn dịch vụ, nhập thông tin và gửi đơn chỉ trong vài giây.</p></div><div className="flex items-center gap-2 rounded-xl border border-border bg-bg-card/70 px-4 py-2.5"><Wallet className="h-4 w-4 text-primary-300"/><div><div className="text-[10px] uppercase tracking-wider text-text-dim">Số dư hiện tại</div><div className="text-sm font-bold text-white">{formatCurrency(balance)}</div></div></div></div></div>
    <div className="grid xl:grid-cols-[1fr_360px] gap-5">
      <Card className="overflow-hidden"><div className="border-b border-border bg-bg-soft/30 px-5 py-4 flex items-center gap-2"><Zap className="h-4 w-4 text-primary-300"/><div><h2 className="text-sm font-semibold text-white">Thông tin đơn hàng</h2><p className="text-xs text-text-dim">Chọn đúng dịch vụ trước khi gửi</p></div></div><form onSubmit={submit} className="p-5 sm:p-6 space-y-5">
        <div><label className="block text-xs font-semibold uppercase tracking-wider text-text-muted mb-2">1. Danh mục</label><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">{catList.map(c=><button type="button" key={c.id} onClick={()=>{setCategoryId(c.id);setServiceId(svcList.find(s=>s.category_id===c.id)?.id??'')}} className={cn('text-left rounded-xl border px-3 py-3 transition-all',categoryId===c.id?'border-primary-500/50 bg-primary-500/10 text-white shadow-glow':'border-border bg-bg-card/50 text-text-muted hover:text-white hover:border-border-strong')}><div className="text-sm font-medium truncate">{c.name}</div><div className="text-[10px] mt-1 text-text-dim">{svcList.filter(s=>s.category_id===c.id).length} dịch vụ</div></button>)}</div></div>
        <div><label className="block text-xs font-semibold uppercase tracking-wider text-text-muted mb-2">2. Dịch vụ</label><select value={serviceId} onChange={e=>setServiceId(e.target.value)} className="w-full h-12 rounded-xl bg-bg-soft/80 border border-border px-4 text-sm text-white focus:outline-none focus:border-primary-500/60 focus:ring-2 focus:ring-primary-500/20">{categoryServices.map(s=><option key={s.id} value={s.id} className="bg-bg-soft">{s.name} — {formatCurrency(Number(s.price)*1000)}/1K</option>)}</select></div>
        {service&&<motion.div key={service.id} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} className="rounded-xl border border-primary-500/20 bg-primary-500/[0.04] p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] uppercase tracking-wider text-primary-300 mb-1">Dịch vụ đang chọn</div><h3 className="text-base font-semibold text-white">{service.name}</h3></div><div className="text-right"><div className="text-[10px] text-text-dim">Giá / 1K</div><div className="text-lg font-bold text-gradient-primary">{formatCurrency(Number(service.price)*1000)}</div></div></div><p className="text-xs leading-5 text-text-muted mt-2">{service.description||'Dịch vụ mạng xã hội được cung cấp qua hệ thống 9L Media.'}</p><div className="flex flex-wrap gap-1.5 mt-3">{service.refill&&<Badge tone="success" size="sm"><RefreshCw className="h-3 w-3"/> Refill</Badge>}{service.cancel&&<Badge tone="danger" size="sm"><XCircle className="h-3 w-3"/> Cancel</Badge>}{service.average_time&&<Badge tone="neutral" size="sm"><Clock className="h-3 w-3"/> {service.average_time}</Badge>}</div></motion.div>}
        <div className="grid sm:grid-cols-2 gap-4"><Input label="Link / URL" name="link" placeholder="https://facebook.com/..." value={link} onChange={e=>setLink(e.target.value)} leftIcon={<Link2 className="h-4 w-4"/>} error={linkError||undefined}/><Input label="Số lượng" name="quantity" type="number" placeholder="100" value={quantity} onChange={e=>setQuantity(Number(e.target.value))} leftIcon={<Hash className="h-4 w-4"/>} hint={service?`Min ${formatNumber(service.minimum)} · Max ${formatNumber(service.maximum)}`:''} error={qtyError||undefined}/></div>
        {balanceError&&<div className="flex items-center gap-2 text-sm text-danger-400 rounded-xl border border-danger-500/20 bg-danger/5 px-3.5 py-3"><AlertCircle className="h-4 w-4 shrink-0"/>{balanceError}</div>}
        {success&&<motion.div initial={{opacity:0,y:-5}} animate={{opacity:1,y:0}} className="flex items-center gap-2 text-sm text-success-400 rounded-xl bg-success/10 border border-success/30 px-3.5 py-3"><CheckCircle2 className="h-4 w-4"/>Đơn hàng đã được tạo thành công! <span className="text-text-muted">Bạn có thể theo dõi trong Đơn hàng.</span></motion.div>}
        <Button type="submit" size="lg" fullWidth loading={submitting} disabled={!canSubmit}>{charge>0?`Xác nhận đặt đơn · ${formatCurrency(charge)}`:'Xác nhận đặt đơn'}<ChevronRight className="h-4 w-4"/></Button>
      </form></Card>
      <div className="space-y-4"><Card className="overflow-hidden"><div className="bg-gradient-to-r from-primary-500/10 to-secondary-500/10 border-b border-border px-5 py-4"><h3 className="text-sm font-semibold text-white">Tóm tắt & thanh toán</h3><p className="text-xs text-text-dim mt-0.5">Kiểm tra trước khi xác nhận</p></div><div className="p-5 space-y-4"><div className="rounded-xl border border-border bg-bg-soft/40 p-3.5"><div className="text-[10px] uppercase tracking-wider text-text-dim">Dịch vụ</div><div className="text-sm font-semibold text-white mt-1 line-clamp-2">{service?.name??'Chưa chọn dịch vụ'}</div></div><div className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-text-muted">Đơn giá</span><span className="text-white">{service?formatCurrency(Number(service.price)*1000)+'/1K':'—'}</span></div><div className="flex justify-between"><span className="text-text-muted">Số lượng</span><span className="text-white">{formatNumber(quantity)}</span></div><div className="h-px bg-border"/><div className="flex justify-between items-end"><span className="text-text-muted">Tổng thanh toán</span><span className="text-xl font-bold text-gradient-primary">{formatCurrency(charge)}</span></div><div className="flex justify-between"><span className="text-text-muted">Số dư sau đơn</span><span className={balance-charge<0?'text-danger-400':'text-white'}>{formatCurrency(balance-charge)}</span></div></div></div></Card><Card className="p-5"><div className="flex items-center gap-2 mb-3"><Info className="h-4 w-4 text-primary-300"/><h3 className="text-sm font-semibold text-white">Lưu ý khi đặt đơn</h3></div><ul className="space-y-2 text-xs leading-5 text-text-muted"><li>• Kiểm tra link trước khi xác nhận.</li><li>• Không đặt trùng nhiều đơn trên cùng một link nếu dịch vụ không hỗ trợ.</li><li>• Đơn lỗi do hệ thống sẽ được xử lý theo trạng thái provider.</li></ul></Card></div>
    </div>
  </div>;
}
