import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Search, Eye, XCircle, RefreshCw, CheckCircle2, Clock3, Activity, CircleDollarSign, Filter } from 'lucide-react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { OrderStatusBadge } from '@/components/ui/Badge';
import { Input } from '@/components/ui/Input';
import { Select } from '@/components/ui/Select';
import { Modal } from '@/components/ui/Modal';
import { TablePagination, EmptyState, PageHeader } from '@/components/ui/Table';
import { useToast } from '@/lib/toast';
import { useQuery } from '@/lib/useQuery';
import { fetchAllOrders, updateOrderStatus, syncAllOrders } from '@/lib/admin';
import { formatCurrency, formatDate } from '@/lib/utils';
import type { IAdminOrder } from '@/lib/types';

const PER_PAGE = 10;
export function AdminOrdersPage() {
  const { toast } = useToast();
  const [statusFilter,setStatusFilter]=useState('all'); const [search,setSearch]=useState(''); const [page,setPage]=useState(1); const [detailOrder,setDetailOrder]=useState<IAdminOrder|null>(null); const [actionLoading,setActionLoading]=useState<string|null>(null); const [syncing,setSyncing]=useState(false);
  const {data:orders,loading,refetch}=useQuery(()=>fetchAllOrders(200,0,statusFilter),[statusFilter]);
  useEffect(()=>setPage(1),[statusFilter,search]);
  const handleSync=async()=>{setSyncing(true);try{const r=await syncAllOrders();toast(r.success?`Đã đồng bộ ${r.synced??0} đơn hàng`:(r.message??'Đồng bộ thất bại'),r.success?'success':'error');refetch()}catch(e:any){toast(e.message??'Lỗi','error')}finally{setSyncing(false)}};
  const handleStatus=async(id:string,status:string)=>{setActionLoading(id);try{await updateOrderStatus(id,status);toast('Đã cập nhật trạng thái','success');refetch();if(detailOrder?.id===id)setDetailOrder({...detailOrder,status:status as any})}catch(e:any){toast(e.message??'Lỗi','error')}finally{setActionLoading(null)}};
  const list=orders??[]; const filtered=list.filter(o=>!search||o.username.toLowerCase().includes(search.toLowerCase())||o.service_name?.toLowerCase().includes(search.toLowerCase())||o.id.includes(search)); const paginated=filtered.slice((page-1)*PER_PAGE,page*PER_PAGE);
  const stats=[['Tổng đơn',filtered.length,ListIcon],['Chờ xử lý',filtered.filter(o=>o.status==='PENDING').length,Clock3],['Đang chạy',filtered.filter(o=>o.status==='PROCESSING').length,Activity],['Doanh thu',formatCurrency(filtered.reduce((s,o)=>s+Number(o.charge||0),0)),CircleDollarSign]] as const;
  return <div className="space-y-5">
    <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><PageHeader title="Quản lý đơn hàng" subtitle="Theo dõi, xử lý và kiểm soát toàn bộ đơn hàng"/><Button variant="outline" size="sm" loading={syncing} leftIcon={<RefreshCw className="h-3.5 w-3.5"/>} onClick={handleSync}>Đồng bộ Provider</Button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{stats.map(([label,value,Icon],i)=><motion.div key={label} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} transition={{delay:i*.04}}><Card className="p-4"><div className="flex items-center justify-between"><div><p className="text-xs text-text-dim">{label}</p><p className="text-xl font-bold text-white mt-1">{value}</p></div><div className="h-9 w-9 rounded-xl bg-primary-500/10 border border-primary-500/20 flex items-center justify-center"><Icon className="h-4 w-4 text-primary-300"/></div></div></Card></motion.div>)}</div>
    <Card className="p-3"><div className="flex flex-col lg:flex-row gap-3"><div className="flex-1"><Input placeholder="Tìm user, dịch vụ, Order ID..." value={search} onChange={e=>setSearch(e.target.value)} leftIcon={<Search className="h-4 w-4"/>}/></div><div className="flex items-center gap-2 text-xs text-text-dim"><Filter className="h-4 w-4"/><Select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} containerClassName="w-44"><option value="all">Tất cả trạng thái</option><option value="PENDING">Chờ xử lý</option><option value="PROCESSING">Đang chạy</option><option value="COMPLETED">Hoàn thành</option><option value="PARTIAL">Một phần</option><option value="CANCELED">Đã hủy</option><option value="FAILED">Lỗi</option></Select></div></div></Card>
    <Card className="overflow-hidden">{loading?<div className="p-6 space-y-2">{Array.from({length:7}).map((_,i)=><div key={i} className="skeleton h-12 rounded-lg"/>)}</div>:paginated.length===0?<EmptyState title="Không có đơn hàng phù hợp"/>:<><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-text-dim border-b border-border bg-bg-soft/30"><th className="font-medium py-3 px-4">ID</th><th className="font-medium py-3 px-4">Người dùng</th><th className="font-medium py-3 px-4">Dịch vụ</th><th className="font-medium py-3 px-4 text-right">SL</th><th className="font-medium py-3 px-4 text-right">Chi phí</th><th className="font-medium py-3 px-4">Trạng thái</th><th className="font-medium py-3 px-4">Ngày tạo</th><th className="font-medium py-3 px-4 text-right">Hành động</th></tr></thead><tbody>{paginated.map((o,i)=><motion.tr key={o.id} initial={{opacity:0}} animate={{opacity:1}} transition={{delay:i*.02}} className="border-b border-border/40 hover:bg-white/[.025]"><td className="py-3 px-4 font-mono text-xs text-primary-300">#{o.id.slice(0,8)}</td><td className="py-3 px-4 text-white font-medium">{o.username}</td><td className="py-3 px-4"><div className="text-white">{o.service_name}</div><div className="text-xs text-text-dim">{o.category_name}</div></td><td className="py-3 px-4 text-right text-text-muted">{o.quantity}</td><td className="py-3 px-4 text-right font-medium text-white">{formatCurrency(o.charge)}</td><td className="py-3 px-4"><OrderStatusBadge status={o.status}/></td><td className="py-3 px-4 text-xs text-text-dim whitespace-nowrap">{formatDate(o.created_at)}</td><td className="py-3 px-4"><div className="flex justify-end gap-1"><button onClick={()=>setDetailOrder(o)} className="h-8 w-8 rounded-lg flex items-center justify-center text-text-muted hover:text-white hover:bg-white/[.06]"><Eye className="h-4 w-4"/></button>{o.status==='PENDING'&&<><button onClick={()=>handleStatus(o.id,'PROCESSING')} disabled={actionLoading===o.id} className="h-8 w-8 rounded-lg text-primary-300 hover:bg-primary-500/10"><RefreshCw className="h-4 w-4 mx-auto"/></button><button onClick={()=>handleStatus(o.id,'CANCELED')} disabled={actionLoading===o.id} className="h-8 w-8 rounded-lg text-danger hover:bg-danger/10"><XCircle className="h-4 w-4 mx-auto"/></button></>}{o.status==='PROCESSING'&&<button onClick={()=>handleStatus(o.id,'COMPLETED')} disabled={actionLoading===o.id} className="h-8 w-8 rounded-lg text-success hover:bg-success/10"><CheckCircle2 className="h-4 w-4 mx-auto"/></button>}</div></td></motion.tr>)}</tbody></table></div><TablePagination page={page} perPage={PER_PAGE} total={filtered.length} onPageChange={setPage}/></>}</Card>
    <Modal open={!!detailOrder} onClose={()=>setDetailOrder(null)} title="Chi tiết đơn hàng" size="lg">{detailOrder&&<div className="space-y-4"><div className="rounded-xl border border-primary-500/20 bg-primary-500/[.04] p-4 flex items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-wider text-text-dim">Order ID</p><p className="font-mono text-sm text-primary-300 mt-1">{detailOrder.id}</p></div><OrderStatusBadge status={detailOrder.status}/></div><div className="grid sm:grid-cols-2 gap-4">{[['Người dùng',detailOrder.username],['Dịch vụ',detailOrder.service_name],['Danh mục',detailOrder.category_name],['Link',detailOrder.link],['Số lượng',String(detailOrder.quantity)],['Chi phí',formatCurrency(detailOrder.charge)],['Vốn',formatCurrency(detailOrder.cost)],['Lợi nhuận',formatCurrency(detailOrder.profit)],['Start count',String(detailOrder.start_count??'-')],['Còn lại',String(detailOrder.remains??'-')],['Ngày tạo',formatDate(detailOrder.created_at)]].map(([l,v])=><div key={l}><span className="text-xs text-text-dim">{l}</span><p className="text-sm text-white mt-0.5 break-all">{v}</p></div>)}</div><div className="flex gap-2 pt-3 border-t border-border">{['PENDING','PROCESSING'].includes(detailOrder.status)&&<><Button size="sm" variant="success" leftIcon={<CheckCircle2 className="h-4 w-4"/>} loading={actionLoading===detailOrder.id} onClick={()=>handleStatus(detailOrder.id,'COMPLETED')}>Hoàn thành</Button><Button size="sm" variant="danger" leftIcon={<XCircle className="h-4 w-4"/>} loading={actionLoading===detailOrder.id} onClick={()=>handleStatus(detailOrder.id,'CANCELED')}>Hủy + hoàn tiền</Button></>}</div></div>}</Modal>
  </div>;
}
function ListIcon(){return <Activity className="h-4 w-4"/>}
